version: '3'
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: syncthing-home-server
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/lib/volumes/syncthing:/var/syncthing:Z
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    hostname: jellyfin-home-server
    volumes:
      - /var/lib/volumes/jellyfin/config:/config:Z
      - /var/lib/volumes/jellyfin/cache:/cache:Z
      - /var/lib/media/Video/Movies:/media/Movies
      - /var/lib/media/Video/TV:/media/TV
      - /var/lib/media/Video/Kids:/media/Kids
      - /var/lib/media/Audio/All/:/media/Music
    ports:
      - 8096:8096/tcp
    restart: unless-stopped
