version: '3'
services:

  syncthing:
    container_name: syncthing
    image: syncthing/syncthing
    hostname: syncthing-home-server
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/lib/volumes/syncthing:/var/syncthing:Z
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    hostname: jellyfin-home-server
    volumes:
      - /var/lib/volumes/jellyfin/config:/config:Z
      - /var/lib/volumes/jellyfin/cache:/cache:Z
      - /var/lib/media/Video/Movies:/media/Movies:z
      - /var/lib/media/Video/TV:/media/TV:z
      - /var/lib/media/Video/Kids:/media/Kids:z
      - /var/lib/media/Audio/All/:/media/Music:z
    ports:
      - 8096:8096/tcp
    restart: unless-stopped

  autorestic:
    container_name: autorestic
    image: cupcakearmy/autorestic
    hostname: autorestic-home-server
    command: autorestic --config /config/autorestic.yml cron
    volumes:
      - /var/lib/volumes/autorestic/data:/data:Z
      - /var/lib/volumes/autorestic/config:/config:Z
      - /var/lib/media:/media:z
      - /var/lib/backup/Backups/restic-repo:/backup:z

  # Container where traffic goes via a VPN
  #   test with: docker-compose exec vpn bash -c "curl ipv4.canhazip.com"
  #   ports are exposured to any containers using 'network_mode: service:vpn'
  vpn:
    container_name: vpn
    image: dperson/openvpn-client:latest
    cap_add:
      - net_admin
    restart: unless-stopped
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/lib/volumes/vpn:/vpn:Z
    security_opt:
      - label:disable
    ports:
      - 9091:9091 # transmission web ui
      - 8081:8081 # sickchill web ui
    networks:
      - bridge_vpn
    entrypoint: ["/sbin/tini", "--", "/usr/bin/openvpn.sh", "-d"]

  transmission:
    container_name: transmission
    image: dperson/transmission
    restart: unless-stopped
    environment:
      - USERID=1000
      - GROUPID=1000
      - TR_DOWNLOAD_DIR=/var/lib/transmission-daemon/finished
      - TR_INCOMPLETE_DIR_ENABLED=true
      - TR_INCOMPLETE_DIR=/var/lib/transmission-daemon/incomplete
      - TR_WATCH_DIR_ENABLED=true
      - TR_WATCH_DIR=/var/lib/transmission-daemon/torrents
    volumes:
      - /var/lib/volumes/transmission/sickchill:/sickchill:z
      - /var/lib/volumes/transmission/daemon:/var/lib/transmission-daemon:Z
    network_mode: service:vpn

  sickchill:
    container_name: sickchill
    image: sickchill/sickchill:develop
    restart: unless-stopped
    volumes:
      - /var/lib/volumes/sickchill/config:/config:Z
      - /var/lib/volumes/sickchill/data:/data:Z
      - /var/lib/volumes/transmission/sickchill:/transmission:z
      - /var/lib/media/Video/TV:/shows:z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: service:vpn

networks:
  bridge_vpn:
